// source: consulta.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.consultanotas.ConsultaNotasReply', null, global);
goog.exportSymbol('proto.consultanotas.ConsultaNotasRequest', null, global);
goog.exportSymbol('proto.consultanotas.HealthCheckReply', null, global);
goog.exportSymbol('proto.consultanotas.HealthCheckRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.consultanotas.ConsultaNotasRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.consultanotas.ConsultaNotasRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.consultanotas.ConsultaNotasRequest.displayName = 'proto.consultanotas.ConsultaNotasRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.consultanotas.ConsultaNotasReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.consultanotas.ConsultaNotasReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.consultanotas.ConsultaNotasReply.displayName = 'proto.consultanotas.ConsultaNotasReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.consultanotas.HealthCheckRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.consultanotas.HealthCheckRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.consultanotas.HealthCheckRequest.displayName = 'proto.consultanotas.HealthCheckRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.consultanotas.HealthCheckReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.consultanotas.HealthCheckReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.consultanotas.HealthCheckReply.displayName = 'proto.consultanotas.HealthCheckReply';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.consultanotas.ConsultaNotasRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.consultanotas.ConsultaNotasRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.consultanotas.ConsultaNotasRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.consultanotas.ConsultaNotasRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    requisitante: jspb.Message.getFieldWithDefault(msg, 1, ""),
    documento: jspb.Message.getFieldWithDefault(msg, 2, ""),
    cnpj: jspb.Message.getFieldWithDefault(msg, 3, ""),
    chavenfe: jspb.Message.getFieldWithDefault(msg, 4, ""),
    handlecertificado: jspb.Message.getFieldWithDefault(msg, 5, ""),
    ambiente: jspb.Message.getFieldWithDefault(msg, 6, ""),
    uf: jspb.Message.getFieldWithDefault(msg, 7, ""),
    versaomanual: jspb.Message.getFieldWithDefault(msg, 8, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.consultanotas.ConsultaNotasRequest}
 */
proto.consultanotas.ConsultaNotasRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.consultanotas.ConsultaNotasRequest;
  return proto.consultanotas.ConsultaNotasRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.consultanotas.ConsultaNotasRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.consultanotas.ConsultaNotasRequest}
 */
proto.consultanotas.ConsultaNotasRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequisitante(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDocumento(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCnpj(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setChavenfe(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setHandlecertificado(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setAmbiente(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setUf(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersaomanual(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.consultanotas.ConsultaNotasRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.consultanotas.ConsultaNotasRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.consultanotas.ConsultaNotasRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.consultanotas.ConsultaNotasRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequisitante();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDocumento();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getCnpj();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getChavenfe();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getHandlecertificado();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getAmbiente();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getUf();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getVersaomanual();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
};


/**
 * optional string requisitante = 1;
 * @return {string}
 */
proto.consultanotas.ConsultaNotasRequest.prototype.getRequisitante = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.consultanotas.ConsultaNotasRequest} returns this
 */
proto.consultanotas.ConsultaNotasRequest.prototype.setRequisitante = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string documento = 2;
 * @return {string}
 */
proto.consultanotas.ConsultaNotasRequest.prototype.getDocumento = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.consultanotas.ConsultaNotasRequest} returns this
 */
proto.consultanotas.ConsultaNotasRequest.prototype.setDocumento = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string cnpj = 3;
 * @return {string}
 */
proto.consultanotas.ConsultaNotasRequest.prototype.getCnpj = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.consultanotas.ConsultaNotasRequest} returns this
 */
proto.consultanotas.ConsultaNotasRequest.prototype.setCnpj = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string chavenfe = 4;
 * @return {string}
 */
proto.consultanotas.ConsultaNotasRequest.prototype.getChavenfe = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.consultanotas.ConsultaNotasRequest} returns this
 */
proto.consultanotas.ConsultaNotasRequest.prototype.setChavenfe = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string handlecertificado = 5;
 * @return {string}
 */
proto.consultanotas.ConsultaNotasRequest.prototype.getHandlecertificado = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.consultanotas.ConsultaNotasRequest} returns this
 */
proto.consultanotas.ConsultaNotasRequest.prototype.setHandlecertificado = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string ambiente = 6;
 * @return {string}
 */
proto.consultanotas.ConsultaNotasRequest.prototype.getAmbiente = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.consultanotas.ConsultaNotasRequest} returns this
 */
proto.consultanotas.ConsultaNotasRequest.prototype.setAmbiente = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string uf = 7;
 * @return {string}
 */
proto.consultanotas.ConsultaNotasRequest.prototype.getUf = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.consultanotas.ConsultaNotasRequest} returns this
 */
proto.consultanotas.ConsultaNotasRequest.prototype.setUf = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string versaomanual = 8;
 * @return {string}
 */
proto.consultanotas.ConsultaNotasRequest.prototype.getVersaomanual = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.consultanotas.ConsultaNotasRequest} returns this
 */
proto.consultanotas.ConsultaNotasRequest.prototype.setVersaomanual = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.consultanotas.ConsultaNotasReply.prototype.toObject = function(opt_includeInstance) {
  return proto.consultanotas.ConsultaNotasReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.consultanotas.ConsultaNotasReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.consultanotas.ConsultaNotasReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    message: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.consultanotas.ConsultaNotasReply}
 */
proto.consultanotas.ConsultaNotasReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.consultanotas.ConsultaNotasReply;
  return proto.consultanotas.ConsultaNotasReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.consultanotas.ConsultaNotasReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.consultanotas.ConsultaNotasReply}
 */
proto.consultanotas.ConsultaNotasReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.consultanotas.ConsultaNotasReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.consultanotas.ConsultaNotasReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.consultanotas.ConsultaNotasReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.consultanotas.ConsultaNotasReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string message = 1;
 * @return {string}
 */
proto.consultanotas.ConsultaNotasReply.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.consultanotas.ConsultaNotasReply} returns this
 */
proto.consultanotas.ConsultaNotasReply.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.consultanotas.HealthCheckRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.consultanotas.HealthCheckRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.consultanotas.HealthCheckRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.consultanotas.HealthCheckRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.consultanotas.HealthCheckRequest}
 */
proto.consultanotas.HealthCheckRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.consultanotas.HealthCheckRequest;
  return proto.consultanotas.HealthCheckRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.consultanotas.HealthCheckRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.consultanotas.HealthCheckRequest}
 */
proto.consultanotas.HealthCheckRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.consultanotas.HealthCheckRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.consultanotas.HealthCheckRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.consultanotas.HealthCheckRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.consultanotas.HealthCheckRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.consultanotas.HealthCheckReply.prototype.toObject = function(opt_includeInstance) {
  return proto.consultanotas.HealthCheckReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.consultanotas.HealthCheckReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.consultanotas.HealthCheckReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    message: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.consultanotas.HealthCheckReply}
 */
proto.consultanotas.HealthCheckReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.consultanotas.HealthCheckReply;
  return proto.consultanotas.HealthCheckReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.consultanotas.HealthCheckReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.consultanotas.HealthCheckReply}
 */
proto.consultanotas.HealthCheckReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.consultanotas.HealthCheckReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.consultanotas.HealthCheckReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.consultanotas.HealthCheckReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.consultanotas.HealthCheckReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessage();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 message = 1;
 * @return {number}
 */
proto.consultanotas.HealthCheckReply.prototype.getMessage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.consultanotas.HealthCheckReply} returns this
 */
proto.consultanotas.HealthCheckReply.prototype.setMessage = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


goog.object.extend(exports, proto.consultanotas);
